server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

sandbox-host: localhost
sandbox-port: 8181

service:
  location:
    sandbox: http://${sandbox-host}:${sandbox-port}